version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
       - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: event_store
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: PASSW0rd
    command: [--auth]
    volumes:
      - /c/Users/kirchner/event-store/mongo:/data/db