version: '3.1'

services:

  web_scraper:
    image: bagend-web-scraper
    container_name: bagend-web-scraper
    ports:
       - 8090:8090
    environment:
      ASPNETCORE_URLS: http://*:8090
      ASPNETCORE_ENVIRONMENT: Development
      EVENT_API_CONFIG_URL: http://localhost:8091
      MongoDbConfig:Host: mongo
    depends_on:
      - "event_api"

  event_api:
    image: bagend-event-api
    container_name: bagend-event-api
    ports:
       - 8091:8091
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:8091
      EventStoreDatabase:Host: mongo
    depends_on:
      - "mongo"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
       - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: event_store
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: PASSW0rd
    command: mongod --bind_ip_all --auth
    volumes:
      - /home/dev/event-store/mongo:/data/db